---
apiVersion: config.openshift.io/v1
kind: Image
metadata:
  annotations:
    release.openshift.io/create-only: "true"
  name: cluster
spec:
  additionalTrustedCA:
    name: quay-tnc3-config
  registrySources:
    insecureRegistries:      
    - ran-21-kvm.comm.ibm.gsc:5000
