# These manifests apply to every RAN cluster
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  cluster: base-ran


resources:
  
  - 02-config-ingress-label-selector.yaml
  
  - 03-configmap-quay-tnc3.yaml
  - 04-image-addtrustedCA-tnc3.yaml
  
  - 50-ran-enable-sctp.yaml
